version: '3.8'
services:
  web-server:
    build: .
    environment:
      # Docker подставит сюда значение, которое Dokploy записал в переменные окружения
      - SECRET_TEST=${SECRET_TEST}
    ports:
      - "8080:5000"
