name: Deploy to Dokploy

on:
  push:
    branches:
      - main  # Запускаем при пуше в основную ветку

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get all projects for debug
        run: |
          # Используем curl для отправки секрета в API Dokploy
          curl -X GET "https://dokploy.a.dkoldyaev.com/api/project.all" \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json"

      - name: Update Environment Variable in Dokploy
        run: |
          # Используем curl для отправки секрета в API Dokploy
          curl -X POST "https://dokploy.a.dkoldyaev.com/api/application.saveEnvironment" \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "applicationId": "${{ secrets.DOKPLOY_APP_ID }}",
            "env": "",
            "buildArgs": "",
            "buildSecrets": "SECRET_TEST=${{ secrets.TEST }}",
            "createEnvFile": false
          }'

      - name: Trigger Redeploy
        run: |
          # После обновления переменной просим Dokploy пересобрать/перезапустить сервис
          curl -X POST "https://dokploy.a.dkoldyaev.com/api/application.deploy" \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -d '{
            "applicationId": "${{ secrets.DOKPLOY_APP_ID }}",
            "title": "piu-pu",
            "description": "pu-pu"
          }'
